const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
const ALL_PRODUCTS_FAILURE = "ALL_PRODUCTS_FAILURE";
const CLEAR_ERRORS = "CLEAR_ERRORS";
const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE";

export {
    ALL_PRODUCTS_REQUEST,
    ALL_PRODUCTS_SUCCESS,
    ALL_PRODUCTS_FAILURE,
    CLEAR_ERRORS,
    PRODUCT_DETAILS_REQUEST,
    PRODUCT_DETAILS_SUCCESS,
    PRODUCT_DETAILS_FAILURE,
};